'use client';

import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import useSWR from 'swr';
import { fetchApi } from '../lib/fetchApi';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

const fetcher = async (url: string) => {
  const data = await fetchApi(url);
  return data.data || { kwBank: '', articles: [] };
};

const sanitizeArticleBody = (text: string) => {
  if (!text) return "";
  let t = text;
  // 1. Replace legacy congestion provider settings
  t = t.replace(/netsh int tcp set global congestionprovider=ctcp/gi, "Set-NetTCPSetting -SettingName InternetCustom -CongestionProvider CUBIC");
  t = t.replace(/netsh int tcp set global congestionprovider/gi, "Set-NetTCPSetting -SettingName InternetCustom -CongestionProvider");
  
  // 2. Add MMCSS safe wrappers for registry keys inside markdown
  t = t.replace(/SystemProfile\\Tasks\\Games/gi, "SystemProfile\\\\Tasks\\\\Games (Safe Initialized by SysTune)");
  
  // 3. Clean up generic or repetitive CTAs generated by AI
  t = t.replace(/Download SysTune today.*?\./gi, "");
  t = t.replace(/Start optimizing your PC.*?\./gi, "");
  
  // 4. Enforce list formatting
  t = t.replace(/^(\s*)-\s*/gm, "$1- ");
  
  return t.trim();
};


export default function BlogManager() {
  const { data, error, isLoading, mutate } = useSWR('/api/admin/blog-manager', fetcher, {
    revalidateOnFocus: true,
  });

  const [kwBank, setKwBank] = useState('');
  const [isSavingKw, setIsSavingKw] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationStatus, setGenerationStatus] = useState<string>("");

  // Edit/Preview Modal State
  const [editingArticle, setEditingArticle] = useState<any>(null);
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [editTab, setEditTab] = useState<'en' | 'bn' | 'preview'>('en');
  const [isTranslating, setIsTranslating] = useState(false);
  const [isSavingEdit, setIsSavingEdit] = useState(false);
  const [previewLang, setPreviewLang] = useState<'en' | 'bn'>('en');
  const [scheduleMode, setScheduleMode] = useState<'manual' | 'smart'>('manual');

  const handleSmartSchedule = () => {
    let maxFuture = new Date();
    if (data && data.articles) {
      data.articles.forEach((art: any) => {
        if (art.publish_at) {
          try {
            const pubDt = new Date(art.publish_at);
            if (pubDt > maxFuture) {
              maxFuture = pubDt;
            }
          } catch (e) {}
        }
      });
    }
    const suggestedDt = new Date(maxFuture.getTime() + 24 * 60 * 60 * 1000);
    suggestedDt.setHours(12, 0, 0, 0);
    setEditingArticle({ ...editingArticle, publish_at: suggestedDt.toISOString() });
    setScheduleMode('smart');
  };

  useEffect(() => {
    if (data && data.kwBank !== undefined) {
      setKwBank(data.kwBank);
    }
  }, [data]);

  const handleSaveKw = async () => {
    setIsSavingKw(true);
    try {
      await fetchApi('/api/admin/blog-manager', {
        method: 'POST',
        body: JSON.stringify({ action: 'update_kw', kwBank }),
      });
      alert('Keyword bank synchronized to KV Edge.');
      mutate();
    } catch (err: any) {
      alert(`Save failed: ${err.message}`);
    } finally {
      setIsSavingKw(false);
    }
  };

  const handleForceGenerate = async () => {
    const lines = kwBank.split('\n').map(l => l.trim()).filter(l => l.length > 0);
    if (lines.length === 0) {
      alert("Keyword Bank is empty! Add a keyword first.");
      return;
    }
    const topKeyword = lines[0];

    setIsGenerating(true);
    try {
      // STEP 1: Generate Text
      setGenerationStatus("Drafting...");
      const textRes = await fetchApi('/api/admin/generate-text', {
        method: 'POST',
        body: JSON.stringify({ keyword: topKeyword })
      });
      
      if (!textRes.meta || !textRes.meta.cover_image_keyword) {
        throw new Error("Backend failed to provide image keywords");
      }

      const { draft_id, slug, data: markdownData, meta } = textRes;

      // STEP 2: Generate Media
      setGenerationStatus("Generating Media...");
      const mediaRes = await fetchApi('/api/admin/generate-media', {
        method: 'POST',
        body: JSON.stringify({
          slug: slug,
          cover_image_keyword: meta.cover_image_keyword,
          inline_prompt: meta.inline_prompt
        })
      });

      // STEP 3: Save Draft
      setGenerationStatus("Securing...");
      await fetchApi('/api/admin/save-draft', {
        method: 'POST',
        body: JSON.stringify({
          draft_id: draft_id,
          data: markdownData
        })
      });

      // Update Local Keyword Bank
      const suggestedKeywords = markdownData?.new_suggested_keywords || [];
      const currentLines = lines.slice(1);
      const updatedLines = [...currentLines];
      suggestedKeywords.forEach((kw: string) => {
        const cleanKw = kw.trim();
        if (cleanKw && !updatedLines.some(x => x.toLowerCase() === cleanKw.toLowerCase())) {
          updatedLines.push(cleanKw);
        }
      });
      const newKwBank = updatedLines.join('\n');
      setKwBank(newKwBank);
      
      await fetchApi('/api/admin/blog-manager', {
        method: 'POST',
        body: JSON.stringify({ action: 'update_kw', kwBank: newKwBank }),
      });

      mutate();
      
      const { cover, inline } = mediaRes.media_status || {};
      if (inline === 'failed' || inline === 'failed (404/Timeout)') {
        alert(`⚠️ Article Saved, but Inline Image Generation FAILED (Check API limit or Prompts).\nCover Image: ${cover || 'None'}`);
      } else {
        alert(`Article Generated Successfully!\nCover Image: ${cover || 'None'}\nInline Image: ${inline || 'None'}`);
      }
    } catch (err: any) {
      console.error(err);
      setGenerationStatus(`ERROR: ${err.message}`);
      setTimeout(() => {
        setIsGenerating(false);
        setGenerationStatus("");
      }, 5000);
    }
  };

  const handleToggleStatus = async (index: number) => {
    const newArticles = [...(data?.articles || [])];
    const currentStatus = newArticles[index].status || 'Draft';
    const targetStatus = currentStatus === 'Live' ? 'Draft' : 'Live';
    const targetArticle = {
      ...newArticles[index],
      status: targetStatus
    };
    try {
      await fetchApi(`/api/admin/blog-manager/article/${targetArticle.slug}`, {
        method: 'PUT',
        body: JSON.stringify(targetArticle),
      });
      mutate();
    } catch (err: any) {
      alert(`Status toggle failed: ${err.message}`);
    }
  };

  const handleDeleteArticle = async (index: number) => {
    if (!confirm('Permanently delete this article?')) return;
    const targetArticle = data?.articles[index];
    if (!targetArticle || !targetArticle.slug) return;
    try {
      await fetchApi(`/api/admin/blog-manager/article/${targetArticle.slug}`, {
        method: 'DELETE',
      });
      mutate();
    } catch (err: any) {
      alert(`Delete failed: ${err.message}`);
    }
  };

  const handleOpenEditModal = (article: any, index: number) => {
    // Standardize structure
    const standardized = {
      title: article.title || '',
      body: article.body || article.content || '',
      title_bn: article.title_bn || article.title || '',
      body_bn: article.body_bn || article.body || article.content || '',
      publish_at: article.publish_at || article.generated_at || new Date().toISOString(),
      status: article.status || 'Draft',
      slug: article.slug || '',
      rich_content: article.rich_content || null
    };
    setEditingArticle(standardized);
    setEditingIndex(index);
    setEditTab('en');
    setScheduleMode('manual');
  };

  const handleAutoTranslate = async () => {
    if (!editingArticle.title || !editingArticle.body) {
      alert('Please enter English title and body first.');
      return;
    }
    setIsTranslating(true);
    try {
      // 1. Sanitize the English body before sending to translation
      const safeEnglishBody = sanitizeArticleBody(editingArticle.body);
      
      const res = await fetchApi('/api/admin/translate-blog', {
        method: 'POST',
        body: JSON.stringify({
          en_title: editingArticle.title,
          en_body: safeEnglishBody
        })
      });
      setEditingArticle({
        ...editingArticle,
        body: safeEnglishBody,
        title_bn: res.title_bn,
        body_bn: sanitizeArticleBody(res.body_bn)
      });
      alert('Bilingual translation populated successfully!');
    } catch (err: any) {
      alert(`Auto-translation failed: ${err.message}`);
    } finally {
      setIsTranslating(false);
    }
  };

  const handleSaveEdit = async () => {
    if (editingIndex === null || !editingArticle) return;
    setIsSavingEdit(true);
    try {
      const safeBody = sanitizeArticleBody(editingArticle.body);
      const safeBodyBn = sanitizeArticleBody(editingArticle.body_bn);
      const oldArticle = data?.articles[editingIndex];
      
      let newSlug = editingArticle.slug;
      if (!newSlug || editingArticle.title !== oldArticle?.title) {
        newSlug = editingArticle.title
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/(^-|-$)/g, '');
      }

      let richContent = editingArticle.rich_content;
      if (richContent) {
        try {
          const richObj = JSON.parse(richContent);
          richObj.seo_title = editingArticle.title;
          richObj.content_markdown = safeBody;
          richContent = JSON.stringify(richObj);
        } catch (e) {}
      }

      const targetArticle = {
        title: editingArticle.title,
        body: safeBody,
        title_bn: editingArticle.title_bn,
        body_bn: safeBodyBn,
        publish_at: new Date(editingArticle.publish_at).toISOString(),
        status: editingArticle.status,
        slug: newSlug,
        rich_content: richContent,
        generated_at: oldArticle?.generated_at || new Date().toISOString()
      };

      // Delete old key if the slug has changed to prevent orphans
      if (oldArticle && oldArticle.slug && oldArticle.slug !== newSlug) {
        await fetchApi(`/api/admin/blog-manager/article/${oldArticle.slug}`, {
          method: 'DELETE',
        });
      }

      await fetchApi(`/api/admin/blog-manager/article/${newSlug}`, {
        method: 'PUT',
        body: JSON.stringify(targetArticle),
      });

      setEditingArticle(null);
      setEditingIndex(null);
      alert('Article draft synced to cloud edge matrix!');
      mutate();
    } catch (err: any) {
      alert(`Save failed: ${err.message}`);
    } finally {
      setIsSavingEdit(false);
    }
  };

  const handleInstantPublishModal = async () => {
    if (editingIndex === null || !editingArticle) return;
    if (!confirm('Are you sure you want to instantly deploy this article to the live edge matrix?')) return;
    
    setIsSavingEdit(true);
    try {
      const safeBody = sanitizeArticleBody(editingArticle.body);
      const safeBodyBn = sanitizeArticleBody(editingArticle.body_bn);
      const oldArticle = data?.articles[editingIndex];
      
      let newSlug = editingArticle.slug;
      if (!newSlug || editingArticle.title !== oldArticle?.title) {
        newSlug = editingArticle.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      }

      let richContent = editingArticle.rich_content;
      if (richContent) {
        try {
          const richObj = JSON.parse(richContent);
          richObj.seo_title = editingArticle.title;
          richObj.content_markdown = safeBody;
          richContent = JSON.stringify(richObj);
        } catch (e) {}
      }

      const targetArticle = {
        title: editingArticle.title,
        body: safeBody,
        title_bn: editingArticle.title_bn,
        body_bn: safeBodyBn,
        publish_at: new Date().toISOString(),
        status: 'Live',
        slug: newSlug,
        rich_content: richContent,
        generated_at: oldArticle?.generated_at || new Date().toISOString()
      };

      // Delete old key if the slug has changed to prevent orphans
      if (oldArticle && oldArticle.slug && oldArticle.slug !== newSlug) {
        await fetchApi(`/api/admin/blog-manager/article/${oldArticle.slug}`, {
          method: 'DELETE',
        });
      }

      await fetchApi(`/api/admin/blog-manager/article/${newSlug}`, {
        method: 'PUT',
        body: JSON.stringify(targetArticle),
      });

      setEditingArticle(null);
      setEditingIndex(null);
      alert('🚀 Article instantly published to Cloud Edge!');
      mutate();
    } catch (err: any) {
      alert(`Instant Publish failed: ${err.message}`);
    } finally {
      setIsSavingEdit(false);
    }
  };

  const handleDirectPublish = async (index: number) => {
    if (!confirm('Are you sure you want to instantly deploy this article to the live edge matrix?')) return;
    const targetArticle = {
      ...data?.articles[index],
      status: 'Live',
      publish_at: new Date().toISOString()
    };

    try {
      await fetchApi(`/api/admin/blog-manager/article/${targetArticle.slug}`, {
        method: 'PUT',
        body: JSON.stringify(targetArticle),
      });
      alert('🚀 Article directly published to Cloud Edge!');
      mutate();
    } catch (err: any) {
      alert(`Direct Publish failed: ${err.message}`);
    }
  };

  // Convert UTC ISO to Local string for input
  const formatDatetimeForInput = (isoString: string) => {
    try {
      const d = new Date(isoString);
      if (isNaN(d.getTime())) return '';
      const pad = (n: number) => n.toString().padStart(2, '0');
      return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
    } catch (e) {
      return '';
    }
  };

  return (
    <div className="flex flex-col p-4 sm:p-8 lg:p-12 animate-in fade-in duration-700 w-full">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-6 md:mb-10 gap-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-light text-zinc-100 tracking-tight flex items-center gap-3">
            <span className="text-3xl sm:text-4xl text-purple-400 drop-shadow-[0_0_15px_rgba(168,85,247,0.4)]">📰</span>
            AI Blog Manager
          </h1>
          <p className="text-zinc-500 mt-2 text-xs sm:text-sm max-w-xl leading-relaxed">
            Programmatic SEO Orchestration. Manage keyword banks, edit bilingual content, and trigger Gemini Flash content generation pipelines.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 w-full">
        {/* Left Column: Zone A & B */}
        <div className="lg:col-span-4 flex flex-col gap-6">
          <div className="bg-black/40 backdrop-blur-2xl border border-white/[0.06] rounded-2xl p-6 shadow-2xl flex flex-col">
            <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-widest mb-4">Zone A: Keyword Bank</h3>
            <textarea
              value={kwBank}
              onChange={(e) => setKwBank(e.target.value)}
              className="w-full h-64 bg-black/50 border border-white/[0.08] rounded-xl p-4 text-zinc-300 font-mono text-xs focus:outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all resize-none shadow-inner custom-scrollbar"
              placeholder="Enter SEO keywords (one per line)..."
            />
            <button
              onClick={handleSaveKw}
              disabled={isSavingKw}
              className="mt-4 w-full bg-white/[0.05] hover:bg-white/[0.1] border border-white/[0.08] hover:border-cyan-500/50 text-zinc-200 text-sm font-medium py-3 rounded-xl transition-all"
            >
              {isSavingKw ? 'Syncing...' : 'Save Keyword Bank to Cloud'}
            </button>
          </div>

          <div className="bg-black/40 backdrop-blur-2xl border border-white/[0.06] rounded-2xl p-6 shadow-2xl">
            <h3 className="text-sm font-semibold text-purple-400 uppercase tracking-widest mb-4">Zone B: AI Trigger</h3>
            <button
              onClick={handleForceGenerate}
              disabled={isGenerating || !kwBank.trim()}
              className="w-full bg-gradient-to-r from-purple-500 to-indigo-600 hover:from-purple-400 hover:to-indigo-500 border border-purple-400/30 text-white font-medium py-4 rounded-xl shadow-[0_0_20px_rgba(168,85,247,0.2)] hover:shadow-[0_0_30px_rgba(99,102,241,0.4)] transition-all flex justify-center items-center gap-2"
            >
              {isGenerating ? (
                <>
                  <svg className="animate-spin h-5 w-5 text-white" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/></svg>
                  {generationStatus || "Generating Article & Media..."}
                </>
              ) : (
                '⚡ Force Generate Article Now'
              )}
            </button>
          </div>
        </div>

        {/* Right Column: Zone C */}
        <div className="lg:col-span-8 bg-black/40 backdrop-blur-2xl border border-white/[0.06] rounded-2xl p-6 shadow-2xl flex flex-col">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-sm font-semibold text-indigo-400 uppercase tracking-widest">Zone C: Editorial Management Grid</h3>
            <button onClick={() => mutate()} className="text-xs text-zinc-500 hover:text-cyan-400 transition-colors">🔄 Refresh Grid</button>
          </div>
          
          <div className="overflow-x-auto border border-white/[0.04] rounded-xl bg-black/20">
            {isLoading ? (
              <div className="p-8 text-center text-zinc-500 text-sm">Loading articles...</div>
            ) : data?.articles?.length === 0 ? (
              <div className="p-16 text-center text-zinc-500 text-sm italic">No articles drafted yet.</div>
            ) : (
              <div className="text-xs text-zinc-600 px-6 py-2 bg-white/[0.02] border-b border-white/[0.04]">
                💡 Double-click any row to toggle its publishing status (Draft ↔ Live).
              </div>
            )}
            {!isLoading && data?.articles?.length > 0 && (
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-white/[0.02] border-b border-white/[0.04]">
                    <th className="px-6 py-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider">Index</th>
                    <th className="px-6 py-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider">Article Title</th>
                    <th className="px-6 py-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider">Status</th>
                    <th className="px-6 py-4 text-xs font-semibold text-zinc-400 uppercase tracking-wider text-right">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.02]">
                  {data?.articles?.map((article: any, idx: number) => (
                    <tr 
                      key={idx} 
                      onDoubleClick={() => handleToggleStatus(idx)}
                      className="hover:bg-white/[0.02] transition-colors group cursor-pointer select-none"
                    >
                      <td className="px-6 py-4 whitespace-nowrap text-xs text-zinc-500 font-mono">{idx + 1}</td>
                      <td className="px-6 py-4">
                        <div className="text-sm font-medium text-zinc-200 truncate max-w-sm" title={article.title}>{article.title}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                         <span className={`inline-flex items-center px-2 py-1 rounded-full text-[10px] font-semibold tracking-wide uppercase ${article.status === 'Live' ? 'bg-green-500/10 text-green-400 border border-green-500/20 shadow-[0_0_10px_rgba(34,197,94,0.1)]' : 'bg-amber-500/10 text-amber-400 border border-amber-500/20 shadow-[0_0_10px_rgba(245,158,11,0.1)]'}`}>
                           {article.status || 'Draft'}
                         </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right" onDoubleClick={(e) => e.stopPropagation()}>
                        <button 
                          onClick={() => handleDirectPublish(idx)}
                          className="text-xs px-3 py-1.5 rounded mr-2 transition-colors border shadow-[0_0_8px_rgba(16,185,129,0.15)] bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border-emerald-500/20"
                        >
                          🚀 Direct Publish Now
                        </button>
                        <button 
                          onClick={() => handleOpenEditModal(article, idx)}
                          className="text-xs bg-indigo-500/10 text-indigo-400 px-3 py-1.5 rounded mr-2 hover:bg-indigo-500/20 transition-colors"
                        >
                          Preview / Edit
                        </button>
                        <button 
                          onClick={() => handleDeleteArticle(idx)} 
                          className="text-xs bg-red-500/10 text-red-400 px-3 py-1.5 rounded hover:bg-red-500/20 transition-colors"
                        >
                          Delete
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>

      {/* Edit/Preview Modal Dialog */}
      {editingArticle && typeof document !== 'undefined' ? createPortal(
        <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 animate-in fade-in duration-300">
          <div className="bg-zinc-950 border border-white/10 rounded-2xl w-full max-w-7xl max-h-[90vh] flex flex-col shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300">
            {/* Modal Header */}
            <div className="px-6 py-4 bg-white/[0.02] border-b border-white/10 flex justify-between items-center">
              <h2 className="text-lg font-light text-zinc-100 flex items-center gap-2">
                <span className="text-cyan-400">📝</span> Edit / Preview Article (Bilingual)
              </h2>
              <button 
                onClick={() => { setEditingArticle(null); setEditingIndex(null); }}
                className="text-zinc-400 hover:text-white transition-colors text-xl font-light"
              >
                &times;
              </button>
            </div>

            {/* Modal Body Scroll Container */}
            <div className="flex-1 overflow-y-auto p-6 space-y-6 custom-scrollbar">
              {/* Publishing and Scheduling Settings Grid */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-4 bg-white/[0.01] border border-white/[0.04] rounded-xl">
                <div>
                  <label className="block text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-2">Publishing Workflow Status</label>
                  <div className="flex gap-4">
                    <label className={`flex-1 flex items-center justify-center gap-2 cursor-pointer p-3 rounded-xl border transition-all ${editingArticle.status !== 'Live' ? 'bg-amber-500/10 border-amber-500/30 text-amber-400' : 'bg-white/[0.02] border-white/[0.06] text-zinc-500 hover:border-white/10'}`}>
                      <input 
                        type="radio" 
                        name="editStatus" 
                        checked={editingArticle.status !== 'Live'} 
                        onChange={() => setEditingArticle({ ...editingArticle, status: 'Draft' })} 
                        className="sr-only" 
                      />
                      <span className="text-xs font-medium">📁 Keep as Draft</span>
                    </label>
                    <label className={`flex-1 flex items-center justify-center gap-2 cursor-pointer p-3 rounded-xl border transition-all ${editingArticle.status === 'Live' ? 'bg-green-500/10 border-green-500/30 text-green-400' : 'bg-white/[0.02] border-white/[0.06] text-zinc-500 hover:border-white/10'}`}>
                      <input 
                        type="radio" 
                        name="editStatus" 
                        checked={editingArticle.status === 'Live'} 
                        onChange={() => setEditingArticle({ ...editingArticle, status: 'Live' })} 
                        className="sr-only" 
                      />
                      <span className="text-xs font-medium">🚀 Publish (Live)</span>
                    </label>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-cyan-400 uppercase tracking-wider mb-2">Publish Schedule (Local Time)</label>
                  <div className="flex gap-2 mb-2">
                    <button 
                      onClick={() => setScheduleMode('manual')}
                      className={`flex-1 py-1.5 text-xs font-medium rounded border transition-colors ${scheduleMode === 'manual' ? 'bg-cyan-500/20 border-cyan-500/50 text-cyan-400' : 'bg-white/[0.02] border-white/[0.06] text-zinc-500 hover:text-white'}`}
                    >
                      🗓️ Manual Select
                    </button>
                    <button 
                      onClick={handleSmartSchedule}
                      className={`flex-1 py-1.5 text-xs font-medium rounded border transition-colors ${scheduleMode === 'smart' ? 'bg-purple-500/20 border-purple-500/50 text-purple-400' : 'bg-white/[0.02] border-white/[0.06] text-zinc-500 hover:text-white'}`}
                    >
                      🤖 Smart Schedule
                    </button>
                  </div>
                  <input 
                    type="datetime-local" 
                    value={formatDatetimeForInput(editingArticle.publish_at)} 
                    onChange={(e) => {
                      setScheduleMode('manual');
                      setEditingArticle({ ...editingArticle, publish_at: e.target.value ? new Date(e.target.value).toISOString() : new Date().toISOString() });
                    }}
                    className={`w-full bg-black/50 border rounded-xl px-4 py-3 text-sm focus:outline-none transition-all shadow-inner ${scheduleMode === 'smart' ? 'border-purple-500/30 text-purple-200 focus:border-purple-500/50' : 'border-white/[0.08] text-zinc-200 focus:border-cyan-500/50'}`}
                  />
                </div>
              </div>

              {/* Tabbed Editor Container */}
              <div className="border border-white/10 rounded-xl overflow-hidden bg-black/20 flex flex-col min-h-[400px]">
                {/* Tab Navigation */}
                <div className="flex border-b border-white/10 bg-white/[0.02] overflow-x-auto no-scrollbar scroll-smooth">
                  <button 
                    onClick={() => setEditTab('en')}
                    className={`px-6 py-3 text-sm font-medium transition-all shrink-0 ${editTab === 'en' ? 'text-white border-b-2 border-cyan-400 bg-white/[0.04]' : 'text-zinc-500 hover:text-zinc-300'}`}
                  >
                    🇬🇧 English Content
                  </button>
                  <button 
                    onClick={() => setEditTab('bn')}
                    className={`px-6 py-3 text-sm font-medium transition-all shrink-0 ${editTab === 'bn' ? 'text-white border-b-2 border-cyan-400 bg-white/[0.04]' : 'text-zinc-500 hover:text-zinc-300'}`}
                  >
                    🇧🇩 Bengali Translation
                  </button>
                  <button 
                    onClick={() => setEditTab('preview')}
                    className={`px-6 py-3 text-sm font-medium transition-all shrink-0 ${editTab === 'preview' ? 'text-white border-b-2 border-cyan-400 bg-white/[0.04]' : 'text-zinc-500 hover:text-zinc-300'}`}
                  >
                    👀 Live Preview
                  </button>
                </div>

                {/* Tab Content Panels */}
                <div className="flex-1 p-6">
                  {editTab === 'en' && (
                    <div className="space-y-4">
                      <div>
                        <label className="block text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">Article Title (English)</label>
                        <input 
                          type="text" 
                          value={editingArticle.title} 
                          onChange={(e) => setEditingArticle({ ...editingArticle, title: e.target.value })}
                          className="w-full bg-black/50 border border-white/[0.08] rounded-xl px-4 py-3 text-zinc-200 text-sm focus:outline-none focus:border-cyan-500/50 transition-all shadow-inner"
                          placeholder="e.g. Master TCP/IP Performance Tweaks"
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">Markdown Body (English)</label>
                        <textarea 
                          value={editingArticle.body} 
                          onChange={(e) => setEditingArticle({ ...editingArticle, body: e.target.value })}
                          className="w-full h-[500px] bg-black/50 border border-white/[0.08] rounded-xl p-4 text-zinc-300 font-mono text-xs focus:outline-none focus:border-cyan-500/50 transition-all shadow-inner custom-scrollbar"
                          placeholder="Markdown text..."
                        />
                      </div>
                    </div>
                  )}

                  {editTab === 'bn' && (
                    <div className="space-y-4">
                      {/* Auto-Translate Trigger */}
                      <div className="flex justify-end mb-2">
                        <button 
                          onClick={handleAutoTranslate}
                          disabled={isTranslating}
                          className="bg-indigo-500/20 hover:bg-indigo-500/30 border border-indigo-500/50 text-indigo-300 px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center gap-2"
                        >
                          {isTranslating ? (
                            <>
                              <svg className="animate-spin h-3.5 w-3.5 text-purple-400" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none"/><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"/></svg>
                              Translating Core Architecture...
                            </>
                          ) : (
                            '✨ Auto-Translate from English using Gemini AI'
                          )}
                        </button>
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">Article Title (Bengali)</label>
                        <input 
                          type="text" 
                          value={editingArticle.title_bn} 
                          onChange={(e) => setEditingArticle({ ...editingArticle, title_bn: e.target.value })}
                          className="w-full bg-black/50 border border-white/[0.08] rounded-xl px-4 py-3 text-zinc-200 text-sm focus:outline-none focus:border-cyan-500/50 transition-all shadow-inner"
                          placeholder="বাংলা শিরোনাম..."
                        />
                      </div>
                      <div>
                        <label className="block text-xs font-semibold text-zinc-500 uppercase tracking-wider mb-2">Markdown Content Body (Bengali)</label>
                        <textarea 
                          value={editingArticle.body_bn} 
                          onChange={(e) => setEditingArticle({ ...editingArticle, body_bn: e.target.value })}
                          className="w-full h-64 bg-black/50 border border-white/[0.08] rounded-xl p-4 text-zinc-300 font-mono text-xs focus:outline-none focus:border-cyan-500/50 transition-all resize-none shadow-inner custom-scrollbar"
                          placeholder="বাংলা আর্টিকেল..."
                        />
                      </div>
                    </div>
                  )}

                  {editTab === 'preview' && (
                    <div className="space-y-6 flex flex-col min-h-[500px] max-h-[600px]">
                      <div className="flex gap-2 border-b border-white/[0.04] pb-3 shrink-0">
                        <button 
                          onClick={() => setPreviewLang('en')}
                          className={`px-3 py-1.5 text-xs rounded-lg transition-all ${previewLang === 'en' ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30' : 'text-zinc-500 hover:text-zinc-300'}`}
                        >
                          English Preview
                        </button>
                        <button 
                          onClick={() => setPreviewLang('bn')}
                          className={`px-3 py-1.5 text-xs rounded-lg transition-all ${previewLang === 'bn' ? 'bg-cyan-500/20 text-cyan-400 border border-cyan-500/30' : 'text-zinc-500 hover:text-zinc-300'}`}
                        >
                          Bengali Preview
                        </button>
                      </div>
                      
                      <div className="flex-1 overflow-y-auto p-6 bg-zinc-950 border border-white/5 rounded-xl custom-scrollbar space-y-4">
                        <h1 className="text-2xl font-bold text-white border-b border-white/10 pb-3">
                          {previewLang === 'en' ? editingArticle.title : editingArticle.title_bn}
                        </h1>
                        <div className="text-xs text-zinc-500 font-mono">
                          📅 Scheduled: {new Date(editingArticle.publish_at).toLocaleString()}
                        </div>
                        <div className="text-sm text-zinc-300 leading-relaxed font-sans">
                            <ReactMarkdown 
                              remarkPlugins={[remarkGfm]}
                              components={{
                                h1: ({node, ...props}: any) => <h1 className="text-2xl font-bold text-white mt-6 mb-4" {...props} />,
                                h2: ({node, ...props}: any) => <h2 className="text-xl font-bold text-cyan-400 mt-6 mb-3 border-b border-white/10 pb-2" {...props} />,
                                h3: ({node, ...props}: any) => <h3 className="text-lg font-bold text-purple-400 mt-4 mb-2" {...props} />,
                                p: ({node, ...props}: any) => <p className="mb-4" {...props} />,
                                ul: ({node, ...props}: any) => <ul className="list-disc pl-6 mb-4 space-y-2 text-zinc-400" {...props} />,
                                ol: ({node, ...props}: any) => <ol className="list-decimal pl-6 mb-4 space-y-2 text-zinc-400" {...props} />,
                                li: ({node, ...props}: any) => <li {...props} />,
                                a: ({node, href, children, ...props}: any) => <a href={href} target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:text-cyan-300 underline underline-offset-4" {...props}>{children}</a>,
                                strong: ({node, ...props}: any) => <strong className="font-bold text-white" {...props} />,
                                blockquote: ({node, ...props}: any) => <blockquote className="border-l-4 border-indigo-500 pl-4 py-2 my-6 bg-indigo-500/10 italic text-zinc-300 rounded-r-lg" {...props} />,
                                code: ({node, className, children, ...props}: any) => {
                                  const match = /language-(\w+)/.exec(className || '');
                                  const isInline = !match && !String(children).includes('\n');
                                  return isInline ? (
                                    <code className="bg-black/50 text-pink-400 px-1.5 py-0.5 rounded font-mono text-xs border border-white/5" {...props}>
                                      {children}
                                    </code>
                                  ) : (
                                    <pre className="bg-black/60 p-4 rounded-xl overflow-x-auto my-4 border border-white/10 shadow-inner">
                                      <code className="text-emerald-400 font-mono text-sm whitespace-pre" {...props}>
                                        {children}
                                      </code>
                                    </pre>
                                  );
                                },
                                table: ({node, ...props}: any) => <div className="overflow-x-auto my-6 bg-black/30 rounded-xl border border-white/10 p-1"><table className="w-full text-left border-collapse" {...props} /></div>,
                                thead: ({node, ...props}: any) => <thead className="bg-white/5 border-b border-white/10" {...props} />,
                                th: ({node, ...props}: any) => <th className="px-4 py-3 font-semibold text-cyan-300 text-sm whitespace-nowrap" {...props} />,
                                td: ({node, ...props}: any) => <td className="px-4 py-3 border-b border-white/5 text-sm text-zinc-300" {...props} />,
                                img: ({node, src, alt, ...props}: any) => {
                                  let finalSrc = src;
                                  if (src && !src.startsWith('http')) {
                                    const filename = src.split('/').pop()?.replace('.jpg', '') || '';
                                    finalSrc = `https://systune-blog.ramm944.workers.dev/blog/api/cover-image/${filename}`;
                                  }
                                  return <img src={finalSrc} alt={alt} className="w-full max-w-3xl h-auto rounded-xl shadow-[0_0_20px_rgba(0,0,0,0.5)] border border-white/10 my-8 mx-auto block" {...props} />;
                                }
                              }}
                            >
                              {previewLang === 'en' ? editingArticle.body : editingArticle.body_bn}
                            </ReactMarkdown>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>

            {/* Modal Footer */}
            <div className="px-6 py-4 bg-white/[0.02] border-t border-white/10 flex flex-col-reverse sm:flex-row justify-between items-stretch sm:items-center gap-3">
              <button 
                onClick={() => { setEditingArticle(null); setEditingIndex(null); }}
                className="px-5 py-2.5 bg-zinc-800 hover:bg-zinc-700 border border-white/10 text-zinc-300 rounded-xl transition-all text-sm font-medium text-center cursor-pointer"
              >
                Cancel
              </button>
              
              <div className="flex flex-col sm:flex-row gap-3">
                <button 
                  onClick={handleInstantPublishModal}
                  disabled={isSavingEdit}
                  className="px-6 py-2.5 rounded-xl transition-all text-sm font-medium flex items-center justify-center gap-2 bg-gradient-to-r from-emerald-500 to-emerald-600 hover:from-emerald-400 hover:to-emerald-500 border border-emerald-400/30 text-white shadow-[0_0_20px_rgba(16,185,129,0.2)] cursor-pointer"
                >
                  🚀 Instant Publish Now
                </button>
                <button 
                  onClick={handleSaveEdit}
                  disabled={isSavingEdit}
                  className="px-6 py-2.5 rounded-xl transition-all text-sm font-medium flex items-center justify-center gap-2 bg-gradient-to-r from-purple-500 to-indigo-600 hover:from-purple-400 hover:to-indigo-500 border border-purple-400/30 text-white shadow-[0_0_20px_rgba(168,85,247,0.2)] cursor-pointer"
                >
                  {isSavingEdit ? '🔄 Saving Changes...' : '💾 Save Article Edits'}
                </button>
              </div>
            </div>
          </div>
        </div>
      , document.body) : null}
    </div>
  );
}
